[package]
name = "esp32-test"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>"]
edition = "2018"

[dependencies]
# xtensa-lx6-rt = { git = "https://github.com/esp-rs/xtensa-lx6-rt", rev = "89cea20c441d4a1624de99c7278df13af5c211a4" }
xtensa-lx6-rt = { path = "../../projects/xtensa-lx6-rt" }
esp32 = "0.2.2"
# esp32 = { path = "../../hal/esp32-pac"}
esp32-hal = { path = "../../hal/esp32-hal"}

# NOTE: if you change this, remember to change all the scripts
[[bin]]
name = "esp32"
path = "src/main.rs"

[profile.dev]
incremental = false
debug = true
codegen-units = 1

[profile.release]
lto = true
incremental = false
debug = true
codegen-units = 1
