[package]
name = "xtensa-quickstart"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>"]
edition = "2018"

[dependencies]
xtensa-lx6-rt = "0.4.0"
xtensa-lx6 = "0.2.0"
panic-halt = "0.2.0"

[dev-dependencies]
esp32-hal = "0.1.0"

